sudo: false
language: python

matrix:
  include:
    # This is a workaround to make 3.7 running in travis-ci
    # See https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      script: tox
      dist: xenial
      sudo: true

install:
  - pip install tox codecov

script:
  - tox -e py

after_success:
  - cd tests && codecov
